[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xhec-mlops-project-student"
version = "0.0.1"
description = "X-HEC MLOps Project on Abalone age prediction model"
requires-python = ">3.10"

dependencies = [
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "pre-commit>=3.0.0",
    "typer>=0.9.0",
    "rich>=10.0.0",
]
